## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -277.0
accel_x_max: 249.0
accel_y_min: -270.0
accel_y_max: 253.0
accel_z_min: -276.0
accel_z_max: 235.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [30.6658, 8.26017, -17.4224]
magn_ellipsoid_transform: [[0.795134, 0.00760939, 0.00517800], [0.00760939, 0.794974, 0.0340982], [0.00517800, 0.0340982, 0.994126]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -18.35
gyro_average_offset_y: -29.37
gyro_average_offset_z: 0.17
